### ISSUE TITLE
Creat a settings page

### ISSUE THREAD

**Issue by ken1000minus7** [ken1000minus7/Bloggy#21]
There should be a settings option in the dropdown menu that is displayed when clicking on username on navbar

The settings page should have a sidebar for different sections, keep 2 sections for  now profipe and account

On the right of the sidebar current section should be displayed, for now only complete these two sections profile and account

Profile section should display user's details in editable text fields and there should be save option at the  bottom for saving changes made in the details, on clicking you should display a confirmation dialog asking if you want to save the changes (like logout dialog)

You need not implement the saving functionality, just complete the frontend

For account section there should be option to change email address and change password, complete the frontend part only

**Comment by abhinavmalhotra01** [comment]
hello sir ; kindly assign me this issue

**Comment by ken1000minus7** [comment]
Sure

**Comment by abhinavmalhotra01** [comment]
hello sir ; sir should i make separate pages for edit account and edit profiles ? if not , kindly guide me into this ; thanks
and sorry for being late 😢 😞

**Comment by ken1000minus7** [comment]
Not exactly separate pages, the settings page should look something like this
![image](https://user-images.githubusercontent.com/78747188/219454111-f47c9530-2e82-467f-9a1d-b347ecd08a8f.png)
A sidebar on the left and depending on the option selected corresponding page will be displayed on the right
Lemme know if u need more info

**Comment by abhinavmalhotra01** [comment]
ohk sir

**Comment by abhinavmalhotra01** [comment]
hello sir ; sir in profile section , i could only find firstname , lastname and username in profile component , so is that all i need to add ?

**Comment by abhinavmalhotra01** [comment]
![bloggy1](https://user-images.githubusercontent.com/113239170/219944563-05f124b7-ca0c-4f0c-aad7-1a0303c171df.png)
this is the current , i have done

**Comment by ken1000minus7** [comment]
Yeah those fields are enough, just add a circular image on the right as a placeholder for profile pic for now
Also increase the width of each element of the sidebar, or reduce the width of the sidebar, too much space not good

**Comment by abhinavmalhotra01** [comment]
ohk sir ; and sir to get details of user, can i simply use the details as argument (like in comments) or have to do a get req ?

**Comment by ken1000minus7** [comment]
Get req, although displaying actual data not that imp for now, only the ui part imp

**Comment by abhinavmalhotra01** [comment]
ohk sir ; so sir can i just leave dummy data ? :SmileInPain:

**Comment by abhinavmalhotra01** [comment]
![Screenshot 2023-02-20 181031](https://user-images.githubusercontent.com/113239170/220111157-8eded8f6-f84f-4cde-a6d6-0b1c11a778b0.png)
![Screenshot 2023-02-20 181044](https://user-images.githubusercontent.com/113239170/220111175-6a357d23-2dfe-4ac1-9078-cff445812b1b.png)
![Screenshot 2023-02-20 181056](https://user-images.githubusercontent.com/113239170/220111187-96ad8031-3788-4ac7-8af1-bd4a3d010473.png)
sir these are the current pages

**Comment by ken1000minus7** [comment]
Seems good, use a different font and fix too much space in sidebar

**Comment by abhinavmalhotra01** [comment]
and sir wo dummy data :SmileInPain:

**Comment by ken1000minus7** [comment]
Dummy rehne do abhi no prob
