### ISSUE TITLE
Add upvote downvote in comment 

### ISSUE THREAD

**Issue by ken1000minus7** [ken1000minus7/Bloggy#23]
Add upvote downvote buttons in the comment component just like the ones in blog

**Comment by ken1000minus7** [comment]
No need to implement upvoting and all, just need the ui

**Comment by Nikhil7174** [comment]
@ken1000minus7  Please assign me this issue

**Comment by ken1000minus7** [comment]
@Nikhil7174 updates?

**Comment by Nikhil7174** [comment]
@ken1000minus7 By tomorrow I will create a pr for this issue. Sorry for late response
