### ISSUE TITLE
Create `useWidth` hook

### ISSUE THREAD

**Issue by ken1000minus7** [ken1000minus7/Bloggy#24]
Refer how width is being updated in the js files, you need to use the same method to create a hook that returns the current width

Then replace all the width updations with   this hook

**Comment by Nikhil7174** [comment]
@ken1000minus7 Please assign me this issue

**Comment by Nikhil7174** [comment]
@ken1000minus7 I have Added a 'useWindowSize' hook and replaced all the width updations with this hook. Just waiting for pr for issue #30 to be merged. So that i can create a pr for this issue.
