### ISSUE TITLE
Text not visible in dark mode

### ISSUE THREAD

**Issue by ken1000minus7** [ken1000minus7/Bloggy#30]
Textfield text not properly visible in dark mode, the text on blog card also not properly visible
![image](https://user-images.githubusercontent.com/78747188/218332816-5cd58a20-f1d1-4fea-9200-b7f878cc7caa.png)
![image](https://user-images.githubusercontent.com/78747188/218332847-e3af7d04-4fc3-4ba0-af05-ad8139a2e548.png)
![image](https://user-images.githubusercontent.com/78747188/218332878-aefa763e-a80a-424a-a981-38822532c1c4.png)

**Comment by Nikhil7174** [comment]
@ken1000minus7 Sir please assign me this issue. I will create a pr for this by tomorrow only.
