### ISSUE TITLE
Change Lottie Animation

### ISSUE THREAD

**Issue by ken1000minus7** [ken1000minus7/Bloggy#31]
This animation isn't transparent so is not appropriate when using dark mode, replace some other with transparent bg
![image](https://user-images.githubusercontent.com/78747188/218332962-0a3cbc0b-3974-42dc-a23e-ab955bce5899.png)

**Comment by Nikhil7174** [comment]
@ken1000minus7 Please assign me this issue

**Comment by ken1000minus7** [comment]
Complete the issues that are assigned first, then I'll assign you this issue

**Comment by armaanbadhan** [comment]
pls assign

**Comment by ken1000minus7** [comment]
gl
