### ISSUE TITLE
Add a confirmation dialog for blog creation

### ISSUE THREAD

**Issue by ken1000minus7** [ken1000minus7/Bloggy#35]
A confirmation dialog should appear when clicking on create button asking are u sure you want to post this blog along with a lottie anim, like the logout dialog

**Comment by Nikhil7174** [comment]
@ken1000minus7 Please assign me this issue

**Comment by ken1000minus7** [comment]
@Nikhil7174 updates?

**Comment by Nikhil7174** [comment]
@ken1000minus7 my end sem exams are going on pls give me a day or two for this issue

**Comment by ken1000minus7** [comment]
Ok sure
